languages:
   Ruby: true
   JavaScript: false
   Python: false
   PHP: false
engines:
  rubocop:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
exclude_paths:
- lib/qpush/web/public/**/*
